Repository shikhanair/TeachersPetBot, pull requests merged in 2021-09, with the labels that each got.

#13 Basic Q and A Functionality
  src/bot.py
  src/qna.py
Labels: feature-qanda

#16 Event creation
  src/bot.py
  src/db.py
  src/event_creation.py
  src/init_db.sql
  src/office_hours.py
  src/requirements.txt
Labels: feature-officehours

#26 Calendar Updates
  initialize_db_script.py
  src/bot.py
  src/cal.py
  src/event_creation.py
  src/init_db.sql
Labels: feature-calendar
